/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing DocumentAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentAttachmentTests
    {
        // TODO uncomment below to declare an instance variable for DocumentAttachment
        //private DocumentAttachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentAttachment
            //instance = new DocumentAttachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentAttachment
        /// </summary>
        [Test]
        public void DocumentAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentAttachment
            //Assert.IsInstanceOfType<DocumentAttachment> (instance, "variable 'instance' is a DocumentAttachment");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'FileFromContent'
        /// </summary>
        [Test]
        public void FileFromContentTest()
        {
            // TODO unit test for the property 'FileFromContent'
        }
        /// <summary>
        /// Test the property 'FileFromContentName'
        /// </summary>
        [Test]
        public void FileFromContentNameTest()
        {
            // TODO unit test for the property 'FileFromContentName'
        }
        /// <summary>
        /// Test the property 'FileFromUrl'
        /// </summary>
        [Test]
        public void FileFromUrlTest()
        {
            // TODO unit test for the property 'FileFromUrl'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Test]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }

    }

}
