/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing DocumentSigningLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentSigningLogTests
    {
        // TODO uncomment below to declare an instance variable for DocumentSigningLog
        //private DocumentSigningLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentSigningLog
            //instance = new DocumentSigningLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentSigningLog
        /// </summary>
        [Test]
        public void DocumentSigningLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentSigningLog
            //Assert.IsInstanceOfType<DocumentSigningLog> (instance, "variable 'instance' is a DocumentSigningLog");
        }


        /// <summary>
        /// Test the property 'Pdf'
        /// </summary>
        [Test]
        public void PdfTest()
        {
            // TODO unit test for the property 'Pdf'
        }
        /// <summary>
        /// Test the property 'SecurityHash'
        /// </summary>
        [Test]
        public void SecurityHashTest()
        {
            // TODO unit test for the property 'SecurityHash'
        }

    }

}
