/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing Document
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentTests
    {
        // TODO uncomment below to declare an instance variable for Document
        //private Document instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Document
            //instance = new Document();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Document
        /// </summary>
        [Test]
        public void DocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Document
            //Assert.IsInstanceOfType<Document> (instance, "variable 'instance' is a Document");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'FileAsPdf'
        /// </summary>
        [Test]
        public void FileAsPdfTest()
        {
            // TODO unit test for the property 'FileAsPdf'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'FrontendId'
        /// </summary>
        [Test]
        public void FrontendIdTest()
        {
            // TODO unit test for the property 'FrontendId'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'FileFromUrl'
        /// </summary>
        [Test]
        public void FileFromUrlTest()
        {
            // TODO unit test for the property 'FileFromUrl'
        }
        /// <summary>
        /// Test the property 'EventsCallbackUrl'
        /// </summary>
        [Test]
        public void EventsCallbackUrlTest()
        {
            // TODO unit test for the property 'EventsCallbackUrl'
        }
        /// <summary>
        /// Test the property 'FileFromContent'
        /// </summary>
        [Test]
        public void FileFromContentTest()
        {
            // TODO unit test for the property 'FileFromContent'
        }
        /// <summary>
        /// Test the property 'FileFromContentName'
        /// </summary>
        [Test]
        public void FileFromContentNameTest()
        {
            // TODO unit test for the property 'FileFromContentName'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'PrefillTags'
        /// </summary>
        [Test]
        public void PrefillTagsTest()
        {
            // TODO unit test for the property 'PrefillTags'
        }
        /// <summary>
        /// Test the property 'Integrations'
        /// </summary>
        [Test]
        public void IntegrationsTest()
        {
            // TODO unit test for the property 'Integrations'
        }
        /// <summary>
        /// Test the property 'FileFromSf'
        /// </summary>
        [Test]
        public void FileFromSfTest()
        {
            // TODO unit test for the property 'FileFromSf'
        }
        /// <summary>
        /// Test the property 'AutoDeleteDays'
        /// </summary>
        [Test]
        public void AutoDeleteDaysTest()
        {
            // TODO unit test for the property 'AutoDeleteDays'
        }
        /// <summary>
        /// Test the property 'Pdf'
        /// </summary>
        [Test]
        public void PdfTest()
        {
            // TODO unit test for the property 'Pdf'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Signrequest'
        /// </summary>
        [Test]
        public void SignrequestTest()
        {
            // TODO unit test for the property 'Signrequest'
        }
        /// <summary>
        /// Test the property 'ApiUsed'
        /// </summary>
        [Test]
        public void ApiUsedTest()
        {
            // TODO unit test for the property 'ApiUsed'
        }
        /// <summary>
        /// Test the property 'SigningLog'
        /// </summary>
        [Test]
        public void SigningLogTest()
        {
            // TODO unit test for the property 'SigningLog'
        }
        /// <summary>
        /// Test the property 'SecurityHash'
        /// </summary>
        [Test]
        public void SecurityHashTest()
        {
            // TODO unit test for the property 'SecurityHash'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }
        /// <summary>
        /// Test the property 'AutoDeleteAfter'
        /// </summary>
        [Test]
        public void AutoDeleteAfterTest()
        {
            // TODO unit test for the property 'AutoDeleteAfter'
        }

    }

}
