/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing InlinePrefillTags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlinePrefillTagsTests
    {
        // TODO uncomment below to declare an instance variable for InlinePrefillTags
        //private InlinePrefillTags instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlinePrefillTags
            //instance = new InlinePrefillTags();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlinePrefillTags
        /// </summary>
        [Test]
        public void InlinePrefillTagsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlinePrefillTags
            //Assert.IsInstanceOfType<InlinePrefillTags> (instance, "variable 'instance' is a InlinePrefillTags");
        }


        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'CheckboxValue'
        /// </summary>
        [Test]
        public void CheckboxValueTest()
        {
            // TODO unit test for the property 'CheckboxValue'
        }
        /// <summary>
        /// Test the property 'DateValue'
        /// </summary>
        [Test]
        public void DateValueTest()
        {
            // TODO unit test for the property 'DateValue'
        }

    }

}
