/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing InlineTeamMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineTeamMemberTests
    {
        // TODO uncomment below to declare an instance variable for InlineTeamMember
        //private InlineTeamMember instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineTeamMember
            //instance = new InlineTeamMember();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineTeamMember
        /// </summary>
        [Test]
        public void InlineTeamMemberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineTeamMember
            //Assert.IsInstanceOfType<InlineTeamMember> (instance, "variable 'instance' is a InlineTeamMember");
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'IsAdmin'
        /// </summary>
        [Test]
        public void IsAdminTest()
        {
            // TODO unit test for the property 'IsAdmin'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsOwner'
        /// </summary>
        [Test]
        public void IsOwnerTest()
        {
            // TODO unit test for the property 'IsOwner'
        }

    }

}
