/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing RequiredAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequiredAttachmentTests
    {
        // TODO uncomment below to declare an instance variable for RequiredAttachment
        //private RequiredAttachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequiredAttachment
            //instance = new RequiredAttachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequiredAttachment
        /// </summary>
        [Test]
        public void RequiredAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequiredAttachment
            //Assert.IsInstanceOfType<RequiredAttachment> (instance, "variable 'instance' is a RequiredAttachment");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

    }

}
