/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing SignRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SignRequestTests
    {
        // TODO uncomment below to declare an instance variable for SignRequest
        //private SignRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignRequest
            //instance = new SignRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignRequest
        /// </summary>
        [Test]
        public void SignRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignRequest
            //Assert.IsInstanceOfType<SignRequest> (instance, "variable 'instance' is a SignRequest");
        }


        /// <summary>
        /// Test the property 'FromEmail'
        /// </summary>
        [Test]
        public void FromEmailTest()
        {
            // TODO unit test for the property 'FromEmail'
        }
        /// <summary>
        /// Test the property 'FromEmailName'
        /// </summary>
        [Test]
        public void FromEmailNameTest()
        {
            // TODO unit test for the property 'FromEmailName'
        }
        /// <summary>
        /// Test the property 'IsBeingPrepared'
        /// </summary>
        [Test]
        public void IsBeingPreparedTest()
        {
            // TODO unit test for the property 'IsBeingPrepared'
        }
        /// <summary>
        /// Test the property 'PrepareUrl'
        /// </summary>
        [Test]
        public void PrepareUrlTest()
        {
            // TODO unit test for the property 'PrepareUrl'
        }
        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
        /// <summary>
        /// Test the property 'RequiredAttachments'
        /// </summary>
        [Test]
        public void RequiredAttachmentsTest()
        {
            // TODO unit test for the property 'RequiredAttachments'
        }
        /// <summary>
        /// Test the property 'DisableAttachments'
        /// </summary>
        [Test]
        public void DisableAttachmentsTest()
        {
            // TODO unit test for the property 'DisableAttachments'
        }
        /// <summary>
        /// Test the property 'DisableTextSignatures'
        /// </summary>
        [Test]
        public void DisableTextSignaturesTest()
        {
            // TODO unit test for the property 'DisableTextSignatures'
        }
        /// <summary>
        /// Test the property 'DisableText'
        /// </summary>
        [Test]
        public void DisableTextTest()
        {
            // TODO unit test for the property 'DisableText'
        }
        /// <summary>
        /// Test the property 'DisableDate'
        /// </summary>
        [Test]
        public void DisableDateTest()
        {
            // TODO unit test for the property 'DisableDate'
        }
        /// <summary>
        /// Test the property 'DisableEmails'
        /// </summary>
        [Test]
        public void DisableEmailsTest()
        {
            // TODO unit test for the property 'DisableEmails'
        }
        /// <summary>
        /// Test the property 'DisableUploadSignatures'
        /// </summary>
        [Test]
        public void DisableUploadSignaturesTest()
        {
            // TODO unit test for the property 'DisableUploadSignatures'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Who'
        /// </summary>
        [Test]
        public void WhoTest()
        {
            // TODO unit test for the property 'Who'
        }
        /// <summary>
        /// Test the property 'SendReminders'
        /// </summary>
        [Test]
        public void SendRemindersTest()
        {
            // TODO unit test for the property 'SendReminders'
        }
        /// <summary>
        /// Test the property 'Signers'
        /// </summary>
        [Test]
        public void SignersTest()
        {
            // TODO unit test for the property 'Signers'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Test]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Test]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }
        /// <summary>
        /// Test the property 'IntegrationData'
        /// </summary>
        [Test]
        public void IntegrationDataTest()
        {
            // TODO unit test for the property 'IntegrationData'
        }

    }

}
