/* 
 * SignRequest API
 *
 * https://signrequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignRequest.Api;
using SignRequest.Model;
using SignRequest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing SignRequestQuickCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SignRequestQuickCreateTests
    {
        // TODO uncomment below to declare an instance variable for SignRequestQuickCreate
        //private SignRequestQuickCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignRequestQuickCreate
            //instance = new SignRequestQuickCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignRequestQuickCreate
        /// </summary>
        [Test]
        public void SignRequestQuickCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignRequestQuickCreate
            //Assert.IsInstanceOfType<SignRequestQuickCreate> (instance, "variable 'instance' is a SignRequestQuickCreate");
        }


        /// <summary>
        /// Test the property 'FromEmail'
        /// </summary>
        [Test]
        public void FromEmailTest()
        {
            // TODO unit test for the property 'FromEmail'
        }
        /// <summary>
        /// Test the property 'FromEmailName'
        /// </summary>
        [Test]
        public void FromEmailNameTest()
        {
            // TODO unit test for the property 'FromEmailName'
        }
        /// <summary>
        /// Test the property 'IsBeingPrepared'
        /// </summary>
        [Test]
        public void IsBeingPreparedTest()
        {
            // TODO unit test for the property 'IsBeingPrepared'
        }
        /// <summary>
        /// Test the property 'PrepareUrl'
        /// </summary>
        [Test]
        public void PrepareUrlTest()
        {
            // TODO unit test for the property 'PrepareUrl'
        }
        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
        /// <summary>
        /// Test the property 'RequiredAttachments'
        /// </summary>
        [Test]
        public void RequiredAttachmentsTest()
        {
            // TODO unit test for the property 'RequiredAttachments'
        }
        /// <summary>
        /// Test the property 'DisableAttachments'
        /// </summary>
        [Test]
        public void DisableAttachmentsTest()
        {
            // TODO unit test for the property 'DisableAttachments'
        }
        /// <summary>
        /// Test the property 'DisableTextSignatures'
        /// </summary>
        [Test]
        public void DisableTextSignaturesTest()
        {
            // TODO unit test for the property 'DisableTextSignatures'
        }
        /// <summary>
        /// Test the property 'DisableText'
        /// </summary>
        [Test]
        public void DisableTextTest()
        {
            // TODO unit test for the property 'DisableText'
        }
        /// <summary>
        /// Test the property 'DisableDate'
        /// </summary>
        [Test]
        public void DisableDateTest()
        {
            // TODO unit test for the property 'DisableDate'
        }
        /// <summary>
        /// Test the property 'DisableEmails'
        /// </summary>
        [Test]
        public void DisableEmailsTest()
        {
            // TODO unit test for the property 'DisableEmails'
        }
        /// <summary>
        /// Test the property 'DisableUploadSignatures'
        /// </summary>
        [Test]
        public void DisableUploadSignaturesTest()
        {
            // TODO unit test for the property 'DisableUploadSignatures'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Who'
        /// </summary>
        [Test]
        public void WhoTest()
        {
            // TODO unit test for the property 'Who'
        }
        /// <summary>
        /// Test the property 'SendReminders'
        /// </summary>
        [Test]
        public void SendRemindersTest()
        {
            // TODO unit test for the property 'SendReminders'
        }
        /// <summary>
        /// Test the property 'Signers'
        /// </summary>
        [Test]
        public void SignersTest()
        {
            // TODO unit test for the property 'Signers'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Test]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Test]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }
        /// <summary>
        /// Test the property 'IntegrationData'
        /// </summary>
        [Test]
        public void IntegrationDataTest()
        {
            // TODO unit test for the property 'IntegrationData'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'FrontendId'
        /// </summary>
        [Test]
        public void FrontendIdTest()
        {
            // TODO unit test for the property 'FrontendId'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'FileFromUrl'
        /// </summary>
        [Test]
        public void FileFromUrlTest()
        {
            // TODO unit test for the property 'FileFromUrl'
        }
        /// <summary>
        /// Test the property 'EventsCallbackUrl'
        /// </summary>
        [Test]
        public void EventsCallbackUrlTest()
        {
            // TODO unit test for the property 'EventsCallbackUrl'
        }
        /// <summary>
        /// Test the property 'FileFromContent'
        /// </summary>
        [Test]
        public void FileFromContentTest()
        {
            // TODO unit test for the property 'FileFromContent'
        }
        /// <summary>
        /// Test the property 'FileFromContentName'
        /// </summary>
        [Test]
        public void FileFromContentNameTest()
        {
            // TODO unit test for the property 'FileFromContentName'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'PrefillTags'
        /// </summary>
        [Test]
        public void PrefillTagsTest()
        {
            // TODO unit test for the property 'PrefillTags'
        }
        /// <summary>
        /// Test the property 'Integrations'
        /// </summary>
        [Test]
        public void IntegrationsTest()
        {
            // TODO unit test for the property 'Integrations'
        }
        /// <summary>
        /// Test the property 'FileFromSf'
        /// </summary>
        [Test]
        public void FileFromSfTest()
        {
            // TODO unit test for the property 'FileFromSf'
        }
        /// <summary>
        /// Test the property 'AutoDeleteDays'
        /// </summary>
        [Test]
        public void AutoDeleteDaysTest()
        {
            // TODO unit test for the property 'AutoDeleteDays'
        }

    }

}
