/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Signrequest.Client.Client;
using Signrequest.Client.Api;
using Signrequest.Client.Model;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing SignrequestQuickCreateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SignrequestQuickCreateApiTests
    {
        private SignrequestQuickCreateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SignrequestQuickCreateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignrequestQuickCreateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SignrequestQuickCreateApi
            //Assert.IsInstanceOfType(typeof(SignrequestQuickCreateApi), instance, "instance is a SignrequestQuickCreateApi");
        }

        
        /// <summary>
        /// Test SignrequestQuickCreateCreate
        /// </summary>
        [Test]
        public void SignrequestQuickCreateCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SignRequestQuickCreate data = null;
            //var response = instance.SignrequestQuickCreateCreate(data);
            //Assert.IsInstanceOf<SignRequestQuickCreate> (response, "response is SignRequestQuickCreate");
        }
        
    }

}
