/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Signrequest.Client.Client;
using Signrequest.Client.Api;
using Signrequest.Client.Model;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing TeamsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TeamsApiTests
    {
        private TeamsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TeamsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TeamsApi
            //Assert.IsInstanceOfType(typeof(TeamsApi), instance, "instance is a TeamsApi");
        }

        
        /// <summary>
        /// Test TeamsCreate
        /// </summary>
        [Test]
        public void TeamsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Team data = null;
            //var response = instance.TeamsCreate(data);
            //Assert.IsInstanceOf<Team> (response, "response is Team");
        }
        
        /// <summary>
        /// Test TeamsInviteMember
        /// </summary>
        [Test]
        public void TeamsInviteMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string subdomain = null;
            //InviteMember data = null;
            //var response = instance.TeamsInviteMember(subdomain, data);
            //Assert.IsInstanceOf<InviteMember> (response, "response is InviteMember");
        }
        
        /// <summary>
        /// Test TeamsList
        /// </summary>
        [Test]
        public void TeamsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.TeamsList(page, limit);
            //Assert.IsInstanceOf<InlineResponse2007> (response, "response is InlineResponse2007");
        }
        
        /// <summary>
        /// Test TeamsPartialUpdate
        /// </summary>
        [Test]
        public void TeamsPartialUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string subdomain = null;
            //Team data = null;
            //var response = instance.TeamsPartialUpdate(subdomain, data);
            //Assert.IsInstanceOf<Team> (response, "response is Team");
        }
        
        /// <summary>
        /// Test TeamsRead
        /// </summary>
        [Test]
        public void TeamsReadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string subdomain = null;
            //var response = instance.TeamsRead(subdomain);
            //Assert.IsInstanceOf<Team> (response, "response is Team");
        }
        
    }

}
