/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SignRequest.Client;
using SignRequest.Api;
using SignRequest.Model;

namespace SignRequest.Test
{
    /// <summary>
    ///  Class for testing DocumentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DocumentsApiTests
    {
        private DocumentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DocumentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DocumentsApi
            //Assert.IsInstanceOfType(typeof(DocumentsApi), instance, "instance is a DocumentsApi");
        }

        
        /// <summary>
        /// Test DocumentsCreate
        /// </summary>
        [Test]
        public void DocumentsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Document data = null;
            //var response = instance.DocumentsCreate(data);
            //Assert.IsInstanceOf<Document> (response, "response is Document");
        }
        
        /// <summary>
        /// Test DocumentsDelete
        /// </summary>
        [Test]
        public void DocumentsDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //instance.DocumentsDelete(uuid);
            
        }
        
        /// <summary>
        /// Test DocumentsList
        /// </summary>
        [Test]
        public void DocumentsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string externalId = null;
            //string signrequestWho = null;
            //string signrequestFromEmail = null;
            //string status = null;
            //string userEmail = null;
            //string userFirstName = null;
            //string userLastName = null;
            //string created = null;
            //string modified = null;
            //int? page = null;
            //int? limit = null;
            //var response = instance.DocumentsList(externalId, signrequestWho, signrequestFromEmail, status, userEmail, userFirstName, userLastName, created, modified, page, limit);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test DocumentsRead
        /// </summary>
        [Test]
        public void DocumentsReadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.DocumentsRead(uuid);
            //Assert.IsInstanceOf<Document> (response, "response is Document");
        }
        
    }

}
