/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Signrequest.Client.Api;
using Signrequest.Client.Model;
using Signrequest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing DocumentSignerTemplateConf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentSignerTemplateConfTests
    {
        // TODO uncomment below to declare an instance variable for DocumentSignerTemplateConf
        //private DocumentSignerTemplateConf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentSignerTemplateConf
            //instance = new DocumentSignerTemplateConf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentSignerTemplateConf
        /// </summary>
        [Test]
        public void DocumentSignerTemplateConfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentSignerTemplateConf
            //Assert.IsInstanceOfType<DocumentSignerTemplateConf> (instance, "variable 'instance' is a DocumentSignerTemplateConf");
        }


        /// <summary>
        /// Test the property 'SignerIndex'
        /// </summary>
        [Test]
        public void SignerIndexTest()
        {
            // TODO unit test for the property 'SignerIndex'
        }
        /// <summary>
        /// Test the property 'NeedsToSign'
        /// </summary>
        [Test]
        public void NeedsToSignTest()
        {
            // TODO unit test for the property 'NeedsToSign'
        }
        /// <summary>
        /// Test the property 'ApproveOnly'
        /// </summary>
        [Test]
        public void ApproveOnlyTest()
        {
            // TODO unit test for the property 'ApproveOnly'
        }
        /// <summary>
        /// Test the property 'NotifyOnly'
        /// </summary>
        [Test]
        public void NotifyOnlyTest()
        {
            // TODO unit test for the property 'NotifyOnly'
        }
        /// <summary>
        /// Test the property 'InPerson'
        /// </summary>
        [Test]
        public void InPersonTest()
        {
            // TODO unit test for the property 'InPerson'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Placeholders'
        /// </summary>
        [Test]
        public void PlaceholdersTest()
        {
            // TODO unit test for the property 'Placeholders'
        }

    }

}
