/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Signrequest.Client.Api;
using Signrequest.Client.Model;
using Signrequest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2008
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2008Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2008
        //private InlineResponse2008 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2008
            //instance = new InlineResponse2008();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2008
        /// </summary>
        [Test]
        public void InlineResponse2008InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2008
            //Assert.IsInstanceOfType<InlineResponse2008> (instance, "variable 'instance' is a InlineResponse2008");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Test]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
