/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Signrequest.Client.Api;
using Signrequest.Client.Model;
using Signrequest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing InlineIntegrationData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineIntegrationDataTests
    {
        // TODO uncomment below to declare an instance variable for InlineIntegrationData
        //private InlineIntegrationData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineIntegrationData
            //instance = new InlineIntegrationData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineIntegrationData
        /// </summary>
        [Test]
        public void InlineIntegrationDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineIntegrationData
            //Assert.IsInstanceOfType<InlineIntegrationData> (instance, "variable 'instance' is a InlineIntegrationData");
        }


        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Test]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }
        /// <summary>
        /// Test the property 'IntegrationData'
        /// </summary>
        [Test]
        public void IntegrationDataTest()
        {
            // TODO unit test for the property 'IntegrationData'
        }

    }

}
