/* 
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Signrequest.Client.Api;
using Signrequest.Client.Model;
using Signrequest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Signrequest.Client.Test
{
    /// <summary>
    ///  Class for testing Team1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Team1Tests
    {
        // TODO uncomment below to declare an instance variable for Team1
        //private Team1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Team1
            //instance = new Team1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Team1
        /// </summary>
        [Test]
        public void Team1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Team1
            //Assert.IsInstanceOfType<Team1> (instance, "variable 'instance' is a Team1");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Subdomain'
        /// </summary>
        [Test]
        public void SubdomainTest()
        {
            // TODO unit test for the property 'Subdomain'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
